# Generated by Django 5.0 on 2023-12-23 18:18

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('completed', models.BooleanField(db_default=models.Value(True))),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
