# Generated by Django 5.0 on 2023-12-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_travel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ('start_date',)},
        ),
    ]
