# Generated by Django 5.0 on 2023-12-23 18:30

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_travel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='duration',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('end_date'), '-', models.F('start_date')), output_field=models.DurationField()),
        ),
    ]
