# Generated by Django 5.0 on 2023-12-23 18:37

import backend.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.GeneratedField(db_persist=True, expression=backend.core.models.ConcatOp('first_name', models.Value(' '), 'last_name'), output_field=models.TextField()),
        ),
    ]
