# Generated by Django 5.0 on 2023-12-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_options_remove_product_price_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('medal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=9)),
                ('sport', models.CharField(choices=[('Martial Arts', [('judo', 'Judo'), ('karate', 'Karate')]), ('Racket', [('badminton', 'Badminton'), ('tennis', 'Tennis')]), ('unknown', 'Unknown')], max_length=9)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
